P.register("cvfVersion",function(){return{version:"0.1.0.0-2020-05-26"}});
P.when("A","cvfFormDataGenerator","ready").register("cvf-account-switcher",function(f,l){function n(c,d){c.preventDefault();var e=l.retrieveFormData(c.target),h=e.inputData.serializeArray();h.push(b(c.target));f.ajax(window.location.protocol+"//"+window.location.host+e.requestPath,{method:"POST",params:h,success:d,error:a})}function b(a){a=c(a);var b=a.attr("name");b||(b=a.closest(".cvf-account-switcher-sign-out-link").attr("data-name"));var d=a.attr("value");d||(d=a.closest(".cvf-account-switcher-sign-out-link").attr("data-value"));
return{name:b,value:d}}function a(a,b,c){f.trigger(h.error,c)}function d(a){var b=/([^@\s]+)@([a-zA-Z0-9_-]+)(\.[a-zA-Z0-9._-]+)/ig.exec(a);if(null!==b){a=b[1];a=c.trim(a);var d=a.length;if(1!==d){for(var e=a.charAt(0),f=0;f<d-2;f++)e+="*";a=e+=a.charAt(d-1)}a+="@";e=b[2];e=c.trim(e);d=e.length;e=e.charAt(0);for(f=0;f<d-1;f++)e+="*";return a+e+b[3]}b=c.trim(a);a=b.length;if(!(4>=a)){d="";for(e=0;e<a-4;e++)d+="*";b=d+b.substr(a-4,a-1)}return b}function e(){0===c(".cvf-account-switcher-check-mark:visible").length&&
(c(".cvf-account-switcher-check-mark-area").remove(),c(".cvf-account-switcher-profile-details").toggleClass("cvf-account-switcher-profile-details cvf-account-switcher-profile-details-after-account-removed"))}var c=f.$,h={success:"cvf:account_switcher:success",error:"cvf:account_switcher:error"};(function(){var a=c("#ap-account-switcher-container")[0],b=window.MutationObserver||window.WebKitMutationObserver;if(void 0!==a&&void 0!==b){var d=new b(function(a){for(var b=0;b<a.length;b++)if(null!==a[b].addedNodes){e();
d.disconnect();break}});d.observe(a,{attributes:!0,childList:!0,characterData:!0,subtree:!0})}})();(function(){c(".cvf-account-switcher-sign-out-link").live("click",function(a){n(a,function(b){if(b.redirectUrl)window.location=b.redirectUrl,f.trigger("cvf:account_switcher","redirectOnSignOut");else if(b.succeeded){var g="."+c(a.target).attr("class").match(/cvf-account-switcher-account-group-\w+/g)[0];c(g+"-hide").hide();c(g+"-name").text(c("#cvf-account-switcher-sign-out-replace-text").text());c(g+
"-claim").text(d(c(g+"-claim").text()));c(g+"-image").replaceWith(c("<div />").append(c("#cvf-account-switcher-sign-out-replace-image").clone().removeClass("cvf-hidden")).html());c(g+"-button").removeClass("cvf-widget-btn-val cvf-widget-btn-verify-account-switcher");b=b.switchedAccountId;void 0!==b&&c(".cvf-account-switcher-account-group-"+b+"-check-mark").show();e()}else f.trigger(h.error,b)})})})()});
P.when("A","cvfVersion","cvfFormDataGenerator","ready").register("cvf",function(f,l,n){function b(a){function b(a){"string"===typeof u.options.widgetMetricsScope&&"function"===typeof window.uet&&window.uex("ld",u.options.widgetMetricsScope,{wb:1});u.options.spinnerTarget&&u.options.spinnerTarget.hide();a.hasOwnProperty("error")?f.trigger(w.error,a.error):a.redirectUrl?window.location=a.redirectUrl:a.redirect?(f.trigger(w.success,a.token,a.status,a.redirect),u.options.autoDestroy?u.destroy():(d(".cvf-widget-alert").hide(),
a.status?d(".cvf-widget-status-success").show():d(".cvf-widget-status-error").show(),q()),f.trigger("cvf:verification:complete",a.status),D.find(".cvf-widget-btn").unbind("click",m),D.find(".cvf-widget-btn-val").unbind("click",m),f.off(w.success),f.off(w.error)):(D.html(a.replace(/<form/g,"<div").replace(/<\/form/g,"</div")),v())}function m(a,c){a.preventDefault();d(".cvf-widget-alert").hide();u.options.spinnerTarget&&u.options.spinnerTarget.show();var e=n.retrieveFormData(a.target),h=e.inputData.serializeArray();
c&&h.push(n.getNameValue(a.target));f.ajax(p+e.requestPath,{method:"POST",params:h,success:b,error:r})}function g(a){13===a.keyCode&&m(a)}function v(){D.find(".cvf-widget-btn").click(function(a){m(a,!1)});D.find(".cvf-widget-btn-val").click(function(a){m(a,!0)});D.find('input[name="code"]').focus().keypress(g)}function C(a){return function(b,c,d){"timeout"!==c||3<=x?f.trigger(w.error,d):f.delay(a,10*x++)}}function r(a,b,c){u.options.spinnerTarget&&u.options.spinnerTarget.hide();f.trigger(w.error,
c)}function q(){d.each(D.find("input"),function(a,b){var c=d(b);c.attr("disabled","disabled");c.hasClass("a-input-text")?c.addClass("a-form-disabled"):c.hasClass("a-button-input")?c.closest(".a-button").addClass("a-button-disabled"):c.closest(".a-input-text-wrapper").length&&c.closest(".a-input-text-wrapper").addClass("a-form-disabled")});d.each(D.find("a"),function(a,b){var c=d(b);c.hasClass("cvf-widget-link-disable-target")&&c.addClass("cvf-link-disabled")})}var u=this;c++;var w={success:"cvf:"+
c+":success",error:"cvf:"+c+":error"};u.options={};d.extend(u.options,e,a);(function(a){if(1!==d(a.target).length)throw Error("The CVF widget requires a unique element.");if(!d.isFunction(a.onSuccess))throw Error("The CVF widget requires a success callback function.");if(!d.isFunction(a.onError))throw Error("The CVF widget requires an error callback function.");})(u.options);var p=u.options.server,D=d(u.options.target);f.on(w.success,u.options.onSuccess);f.on(w.error,u.options.onError);u.start=function(){if(0===
d.trim(u.options.requestToken).length)throw Error("The CVF widget requires a request token.");var a=p+"/ap/cvf/request.embed",c=u.options.requestToken,e=u.options.requestArbToken,h=u.options.associationHandle,g=u.options.language,m=0===d.trim(e).length,n=0!==d.trim(h).length,q=0!==d.trim(g).length,r={};m?r.requestToken=c:r.arb=e;r.CVFVersion=l.version;r.AUIVersion=P.AUI_BUILD_DATE;q&&(r.language=g);n&&(r["openid.assoc_handle"]=h);"string"===typeof u.options.widgetMetricsScope&&"function"===typeof window.uet&&
window.uet("bb",u.options.widgetMetricsScope,{wb:1});f.ajax(a,{method:"GET",params:r,success:b,error:C(u.start)})};u.destroy=function(){D.html("")};v();var x=0;u.options.autoStart&&u.start()}function a(a){return new b(a)}var d=f.$,e={server:"",target:void 0,requestToken:void 0,requestArbToken:void 0,onSuccess:void 0,onError:void 0,spinnerTarget:void 0,autoStart:!0,autoDestroy:!0,widgetMetricsScope:void 0,associationHandle:void 0,language:void 0},c=0;f.on("cvf:verification:request",function(b){var c=
d("#"+b),e=c.data("token"),g=c.data("spinnerId"),g=d("#"+g);a({target:c,spinnerTarget:g,requestToken:e,onSuccess:function(a,c,d){f.trigger("cvf:verification:complete:"+b,a,c,d)},onError:function(a){f.trigger("cvf:verification:error:"+b,a)},autoStart:!0,autoDestroy:!1})});return{create:a}});
P.when("A","cvf","ready").execute(function(f,l){var n=f.$;n(document).ready(function(){function b(a,b,c){window.location=c;console.log("Client Side: "+a)}function a(a){console.log(a)}var d=n(".cvf-widget-spinner"),e=n("#cvf-widget-content");if(1===e.length){var c=n('[name="requestToken"]').first().attr("value");l.create({target:e,spinnerTarget:d,requestToken:c,onSuccess:b,onError:a,autoStart:!1})}})});
P.when("A").execute(function(f){f.declarative("auth-popup","click",function(f){var n=f.data;f=f.$target.closest("a")[0];(n=window.open(f.href,f.target,n.windowOptions))&&n.focus()})});P.when("A","cvfFormDataGenerator","ready").execute(function(f,l){});
P.when("A","cvfFormDataGenerator","ready").execute(function(f,l){var n=f.$;n(".cvf-widget-btn-val").click(function(b){var a=n(b.target).closest(".cvf-widget-form");b=l.getNameValue(n(b.target));a.append('<input type="hidden" name="'+b.name+'" value="'+b.value+'">').submit()})});
P.when("A","ready").register("cvfFormDataGenerator",function(f){var l=f.$;return{retrieveFormData:function(f){f=l(f).closest(".cvf-widget-form");return{requestPath:f.data("use-only-form-action")?f.attr("action"):"/ap/cvf/"+f.attr("action")+".embed",inputData:f.find(".cvf-widget-input,.cvf-widget-hidden-fields,.cvf-widget-input :input"),form:f}},getNameValue:function(f){f=l(f);var b=f.attr("name");b||(b=f.closest(".cvf-widget-btn-val").attr("data-name"));var a=f.attr("value");a||(a=f.closest(".cvf-widget-btn-val").attr("data-value"));
return{name:b,value:a}}}});P.when("A","ready").register("codeResendTimer",function(f){function l(l,b,a){var d=(new Date).getTime(),e=setInterval(function(){var c=(new Date).getTime()-d,c=l-c;if(0>=c)clearInterval(e),f.$("#timer").html(a);else{var c=Math.floor(c/1E3),h=b.split(" +timeleft+ "),c=h[0].split('"').join("")+c+h[1].split('"').join("");f.$("#timer").html(c)}},100)}return{createTimer:function(f,b,a){return new l(f,b,a)}}});
P.when("A","ready").register("codeAutoVerify",function(f){f=f.$;var l=f("#cvf-auto-verify-form");0<l.length&&(window.submitVerificationCode=function(f){l.find("#cvf-enter-code").val(f);l.submit()})});P.when("A","ready").register("codeAutoReadTimer",function(f){var l=f.$,n=l("#cvf-auto-verification-failed");n.length&&f.delay(function(){n[0].click()},3E4)});